name: orbit
options:
  bundleIdPrefix: com.orbit
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "0.2.9"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "DN4YAHWP2P"
    CODE_SIGN_STYLE: Manual
    SWIFT_VERSION: "5.9"
  configs:
    Debug:
      # Debug: Sign with Developer ID but allow debugging
      CODE_SIGN_IDENTITY: "Developer ID Application"
    Release:
      # Release: Sign with Developer ID + timestamp for notarization
      CODE_SIGN_IDENTITY: "Developer ID Application"
      OTHER_CODE_SIGN_FLAGS: "--timestamp"

targets:
  orbit:
    type: application
    platform: macOS
    sources:
      - path: devfwd
        excludes:
          - "**/.DS_Store"
          - "**/LaunchDaemons/**"
    postBuildScripts:
      - name: Copy LaunchDaemons
        script: |
          mkdir -p "${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchDaemons"
          cp "${SRCROOT}/devfwd/Resources/LaunchDaemons/com.orbit.helper.plist" "${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchDaemons/"
        basedOnDependencyAnalysis: false
    dependencies:
      - target: com.orbit.helper
        embed: true
        codeSign: true
        copy:
          destination: wrapper
          subpath: "Contents/Library/LaunchServices"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.orbit.app
        PRODUCT_NAME: Orbit
        INFOPLIST_FILE: devfwd/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          # Debug: Allow debugger attachment (injects com.apple.security.get-task-allow)
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
        Release:
          # Release: No debug entitlements for notarization
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
    entitlements:
      path: devfwd/Resources/devfwd.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.automation.apple-events: true

  com.orbit.helper:
    type: tool
    platform: macOS
    sources:
      - path: devfwdHelper
        excludes:
          - "**/.DS_Store"
          - "launchd.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.orbit.helper
        PRODUCT_NAME: com.orbit.helper
        SKIP_INSTALL: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
        INFOPLIST_FILE: devfwdHelper/Info.plist
        CREATE_INFOPLIST_SECTION_IN_BINARY: YES
        OTHER_LDFLAGS: "-sectcreate __TEXT __launchd_plist $(SRCROOT)/devfwdHelper/launchd.plist"
      configs:
        Release:
          OTHER_CODE_SIGN_FLAGS: "--timestamp"

  orbitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: devfwdTests
    dependencies:
      - target: orbit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.orbit.app.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"

schemes:
  orbit:
    build:
      targets:
        orbit: all
        com.orbit.helper: all
        orbitTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - orbitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
